# permissions for end users to edit configsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmapsyncoperator
    app.kubernetes.io/managed-by: kustomize
  name: configsync-editor-role
rules:
- apiGroups:
  - apps.my.domain
  resources:
  - configsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.my.domain
  resources:
  - configsyncs/status
  verbs:
  - get
