apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configsync-reader-binding
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: configsync-reader
  apiGroup: rbac.authorization.k8s.io
